<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>chrono-isle-setup</AssemblyName>
    <RootNamespace>ChronoIsle.Setup</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <ProjectReference Include="..\ChronoIsle.Core\ChronoIsle.Core.csproj" />
    <ProjectReference Include="..\ChronoIsle.Hooks\ChronoIsle.Hooks.csproj" />
  </ItemGroup>

</Project>
